#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-schwimmen =						\
	papers/schwimmen/packages.tex					\
	papers/schwimmen/main.tex					\
	papers/schwimmen/01_herangehensweise.tex			\
	papers/schwimmen/02_Naiver_weg.tex				\
	papers/schwimmen/03_auswertung.tex				\
	papers/schwimmen/fig-fluss.tex					\
	papers/schwimmen/fig-ueberquerung.tex				\
	papers/schwimmen/fig-grafiken.tex				\
	papers/schwimmen/references.bib					

