#
# Makefile -- build fluss images
#
# (c) 2024 Prof Dr Andreas Müller
#
all:	fluss.pdf fluss-coord.pdf quadratisch.pdf

fluss.pdf:	fluss.tex
	pdflatex fluss.tex

fluss-coord.pdf:	fluss-coord.tex
	pdflatex fluss-coord.tex

quadratisch.pdf:	quadratisch.tex
	pdflatex quadratisch.tex

